name: flutter_app
description: "A simple Memory Game using the Gyro Sensor to detect Gestures."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  esense_flutter: ^1.0.0
  permission_handler: ^11.3.1
  sensors_plus: ^6.1.1
  settings_ui: ^2.0.2
  fl_chart: ^0.69.2
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
